### ISSUE TITLE
无限刷铜币

### ISSUE THREAD

**Issue by Y-Xiao233** [FalAut/sky1234#1]
<img width="1280" alt="{C32C2BFB-F87D-45cf-AD1C-BFCAA9B99348}" src="https://github.com/FalAut/0xUDF/assets/159413429/8590a56d-3fed-4875-af6a-495df2443040">
主线第一章上方的手册奖励有铜币，可以无限重复领取
<img width="686" alt="{86F35C0D-4A65-407e-B214-2E34D2D23260}" src="https://github.com/FalAut/0xUDF/assets/159413429/8ca9941f-6584-41fb-b1e2-5d0bf20b6837">

**Comment by FalAut** [comment]
感谢你的报告
