### ISSUE TITLE
多人联机时客机玩家无法对1234按u键查询用途，会直接报错崩溃回主界面

### ISSUE THREAD

**Issue by Windows2066** [FalAut/sky1234#11]
[crash-2024-03-02_23.41.44-client.txt](https://github.com/FalAut/sky1234/files/14469910/crash-2024-03-02_23.41.44-client.txt)

**Comment by Windows2066** [comment]
而且崩溃后重新进入多人联机人物模型和动画效果会消失

**Comment by FalAut** [comment]
重启客户端，暂时不要查看闪耀纤维，愤怒印记，小市场，下界之眼，1234的JEI，这些物品的合成都有提示
