### ISSUE TITLE
第一阶段小市场无论单人多人均无法打开界面，右键即崩溃

### ISSUE THREAD

**Issue by Windows2066** [FalAut/sky1234#13]
[crash-2024-03-03_01.21.02-server.txt](https://github.com/FalAut/sky1234/files/14470197/crash-2024-03-03_01.21.02-server.txt)

**Comment by FalAut** [comment]
尝试删除Observable模组？之前没人遇到过这个问题

**Comment by FalAut** [comment]
我大概知道什么问题了，下个版本会修复，谢谢你的报告
