### ISSUE TITLE
滚轮操作物品会一次操作两个的问题

### ISSUE THREAD

**Issue by MoeHero** [FalAut/sky1234#15]
比如从箱子转移1个物品到物品栏，直接用滚轮，理论上应该一次只移动1个，但实际上移动了2个。
经过查看将配置文件 `MouseTweaks.cfg` 的 `WheelTweak` 改为 `0` 就好了。
应该是和另一个mod功能重复。

**Comment by FalAut** [comment]
嗯，谢谢
