### ISSUE TITLE
游玩服务器情况下的崩端

### ISSUE THREAD

**Issue by Wotifra233** [FalAut/sky1234#16]
[crash-2024-03-04_11.30.07-client.txt](https://github.com/FalAut/sky1234/files/14476213/crash-2024-03-04_11.30.07-client.txt)
复现过程 进入服务器 对星星按U（这Bug居然没人反馈？？？）

**Comment by FalAut** [comment]
在这次提交中修复了[https://github.com/FalAut/sky1234/commit/2dc0ebd6be4b4fbb2289ef19a4dce0c0bbe8ed66](url)

**Comment by FalAut** [comment]
已在1.5版本中修复
