### ISSUE TITLE
罐中烈焰的界面问题？

### ISSUE THREAD

**Issue by Jing-Xu718** [FalAut/sky1234#17]
![屏幕截图(408)](https://github.com/FalAut/sky1234/assets/136762268/df70c567-d357-41f7-93ef-7e7be664be9b)
![屏幕截图(409)](https://github.com/FalAut/sky1234/assets/136762268/b99de9f3-e7c2-4bd3-929c-573f630e75fd)
![屏幕截图(410)](https://github.com/FalAut/sky1234/assets/136762268/d8b88a28-d820-44f7-aafd-1f0fc17089db)
右击罐中烈焰后分别会出现这样的界面，然后用储液罐灌入岩浆也不转化烈焰血。

**Comment by FalAut** [comment]
https://www.bilibili.com/video/BV1uU411F7zq/?t=970

**Comment by Jing-Xu718** [comment]
旧版本1.4不知道为啥能输入岩浆但是转化进度不动，换新版1.6已解决
