### ISSUE TITLE
有没有简便的更新整合包的办法?

### ISSUE THREAD

**Issue by jiusun** [FalAut/sky1234#18]
更新好快！赞一个，但是一天更新好几次也太快了吧。
我每次都得重新下载整合包，然后要转移存档、改游戏设置、该按键设置、MOD配置
有没有更新包或其他方便的更新办法？

**Comment by FalAut** [comment]
打开安装包
将overrides里的文件覆盖到你的游戏目录（.minecraft）
若更新了模组，请自行添加

**Comment by jiusun** [comment]
模组的更新、新增，配置文件和脚本的删除还是得手动操作，而且更新的快，还得先看一遍每个版本的更新日志才行😩

**Comment by FalAut** [comment]
你可以等整合包稳定的时候再玩
