### ISSUE TITLE
Linux下运行1.6.2版本整合包时在游戏窗口出现时卡死

### ISSUE THREAD

**Issue by 6QHTSK** [FalAut/sky1234#20]
### 系统版本
系统：ArchLinux
显示服务器：X11和Wayland下均有此问题
HMCL：3.5.6.240

### 错误日志

[完整日志记录](https://pastebin.com/KW8eL9FC)（部分隐私信息已删除）

```
[19:00:45] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:00:46] [Render thread/INFO]: Setting user:  <MYMINECRAFTNAME>
[19:00:46] [Render thread/INFO]: Bypassed Mojang DFU
[19:00:46] [Render thread/INFO]: Instantiating Mojang DFU
[19:00:46] [Render thread/INFO]: Lazy DFU
[19:00:46] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[19:00:46] [Render thread/INFO]: Loaded client.properties
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  9 (X_MapSubwindows)
  Serial number of failed request:  198
  Current serial number in output stream:  198
```

### 尝试过的解决方案（均未成功）

- 切换渲染器至`OpenGL`、`Vulkan`、`软渲染器`（`软渲染器`模式下直接报错退出，其他渲染器模式下窗口卡死，错误日志信息基本一致）
- [CSDN](https://blog.csdn.net/lyn631579741/article/details/124227334)文章建议的安装`bdf-unifont`
- [StackExchange](https://unix.stackexchange.com/questions/629281/gitk-crashes-when-viewing-commit-containing-emoji-x-error-of-failed-request-ba)文章建议的删除`noto-fonts-emoji`

### 补充说明

我测试了同为1.18.2，且Forge版本相对接近的Create Arcane Engineering整合包（Forge版本40.2.9），发现CAE可以正常运行。所以感觉有很大的概率是这个整合包自身的问题，遂发此Issue，希望作者能够排查一下，谢谢。

PS. 似乎1.6.2整合包里的`manifest.json`里的版本号还写着1.6.1（

**Comment by FalAut** [comment]
带师都不会了，我这个菜B更不知道怎么修了
回退版本能解决这个问题吗？

**Comment by FalAut** [comment]
作者没有使用过ArchLinux，很抱歉无法给带师解决问题
如果你有精力的话
可以尝试用二分法排查是哪个模组导致的问题
没有的话就换包吧

**Comment by 6QHTSK** [comment]
不是什么带师（瑟瑟发抖）
尝试了1.5.0-hotfix，1.4.0-hotfix，1.1.0-hotfix，都不太行
回到1.6.2排查了一下模组，结果是KubeJS的问题，删除KubeJS及其附属项就能正常启动了emmm
该不会是作者大大往KubeJS里塞了什么奇奇怪怪的东西吧（

**Comment by FalAut** [comment]
主菜单是用KubeJS UI写的，删除这个模组试试？
也试试删除kubejs/client_scripts里的所有文件

**Comment by 6QHTSK** [comment]
> 主菜单是用KubeJS UI写的，删除这个模组试试？

kubejs-ui 这个模组在测试中是没有导入的，测试只导入了kubejs而没有导入它的附属模组，但是只要导入了kubejs这个模组就会报出上面的错误

>  也试试删除kubejs/client_scripts里的所有文件

删了，照样报。

估计是整合包不支持X11和XWayland环境。

--------

后面我试了[minecraft-wayland](https://github.com/Admicos/minecraft-wayland)跑在原生wayland的这个方案，至少能跑了。

算了，能跑就行emmm
