### ISSUE TITLE
we need a sever please

### ISSUE THREAD

**Issue by dhyhy** [FalAut/sky1234#8]

**Comment by FalAut** [comment]
server or serverpack?

**Comment by dhyhy** [comment]
serverpack

**Comment by dhyhy** [comment]
听说包是国人做的

**Comment by FalAut** [comment]
是的。。我看看能不能做一个服务端

**Comment by dhyhy** [comment]
我想把这玩意丢服务器上玩玩
爽包肯定是要一起分享的
之前玩的是创造抽屉制作人 官方的服务端太抽象了 mod都不全 还是在github上找了一个才跑起来

**Comment by FalAut** [comment]
做好了
https://legacy.curseforge.com/minecraft/modpacks/sky1234/files/5151391
经过测试，应该没有问题

**Comment by dhyhy** [comment]
没了？

**Comment by dhyhy** [comment]
现在链接已经打不开了

**Comment by dhyhy** [comment]
> 做好了 https://legacy.curseforge.com/minecraft/modpacks/sky1234/files/5151391 经过测试，应该没有问题

其实可以给sever端单独开一个tag sever端直接发那边 然后再镜像到 gitee这种国内平台

**Comment by dhyhy** [comment]
其实可以给sever端开个branches

**Comment by FalAut** [comment]
> 其实可以给sever端开个branches

确实，发了
https://github.com/FalAut/sky1234/tree/serverpack
